-sverilog $LAB_PATH/RTL/AXI_INTF.sv
-sverilog $LAB_PATH/RTL/DUAL_PORT_SRAM.sv
-sverilog $LAB_PATH/RTL/DMAC_ENGINE.sv
-sverilog $LAB_PATH/RTL/DATA_PROVIDER.sv
-sverilog $LAB_PATH/RTL/PE.sv
-sverilog $LAB_PATH/RTL/SYSTOLIC_ARRAY.sv
-sverilog $LAB_PATH/RTL/MME_TOP.sv
