//
//
// Generated by Semifore, Inc. csrCompile
//    System Verilog RTL output
//
// Version: 2021.09.01 Build: development Linux 64-bit
//
// Command Line: 
//    /home/ScalableArchiLab/bin/csrCompileLite ../MME.rdl -c ../MME.css -o
//    MME_CFG -t sv
//
// Input files: 
//    ../MME.rdl
//
// Configuration files: 
//    ../MME.css
//
// Generated on: Wed Dec  1 23:30:57 2021
//           by: ScalableArchiLab
//

//
// Addressmap: MME_CFG
//
//   Bus Protocol: AMBA_3_APB
//   Bus Address Units: bytes
//
//   Access: read-write
//   Offset Units: bytes
//   Word size: 4 bytes
//
module MME_CFG (
   output wire [7:0] MAT_CFG_mat_width,
   output wire [31:0] MAT_A_ADDR_start_addr,
   output wire [31:0] MAT_B_ADDR_start_addr,
   output wire [31:0] MAT_C_ADDR_start_addr,
   output wire MME_CMD_start,
   output wire PREADY,
   output wire [31:0] PRDATA,
   input  wire MME_STATUS_done,
   input  wire PSEL,
   input  wire PWRITE,
   input  wire PENABLE,
   input  wire [9:0] PADDR,
   input  wire [31:0] PWDATA,
   input  wire RESET,
   input  wire PCLK
   );

endmodule
